spring.application.name=student-performance-backend

spring.datasource.url=jdbc:mysql://localhost:3306/student_performance_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

security.jwt.secret=student-performance-capstone-secret-key-2026
security.jwt.expiration-ms=86400000

app.admin.username=admin
app.admin.password=admin123

springdoc.swagger-ui.path=/swagger-ui.html
